### ISSUE TITLE
Still problems with bidding! 

### ISSUE THREAD

**Issue by syros1977** [hunterjm/fifa-autobuyer#102] opened 2017-02-07 14:38 UTC
I dont know why, but i have 15 players in my tradepile and some serious problems bidding on them! I dont know, maybe my option settings are bad or something. On the first version it worked perfect with these settings. Can anybody help, or give me a playerlist??

**Comment by hunterjm** [comment] 2017-02-07 15:31
Meaning you placed an initial bid, but keep getting outbid, or the AB just isn't buying anyone? Last night the market was on an uptick, so it is difficult for the AB to turn a profit. I was only able to complete one trade last night.

**Comment by syros1977** [comment] 2017-02-07 15:48
Ok, the ab is just not buying anything! He doesnt even find something to bid on! I had a few bad days earlier but since monday the market seems dead!!

**Comment by Fotospecht** [comment] 2017-02-07 15:57
This is not a problem of this autobuyer, the market is declining at the moment.

**Comment by syros1977** [comment] 2017-02-07 16:33
Ok

**Comment by losersFocus** [comment] 2017-02-07 19:36
Ofc it also depends on your player list and configurations. I made last night 4k net in 5h

**Comment by hunterjm** [comment] 2017-02-08 01:08
Closing as this is due to market fluctuations and not a bug in the program.

**Closed by hunterjm** 2017-02-08 01:08 UTC
