### ISSUE TITLE
Bought players don't get listed.

### ISSUE THREAD

**Issue by Bob930** [hunterjm/fifa-autobuyer#114] opened 2017-02-09 17:50 UTC
I have set a player to be bought for 350 and sold for 450. The programm somehow doesn't list the player after it wins a bid.

**Comment by Fotospecht** [comment] 2017-02-09 18:39
Which player exactly ?

**Comment by mestesso93** [comment] 2017-02-09 20:52
i've got same issues. I think that cause is last update. Simply the bidder win the auction and automatically send players to "unassigned" but the AB doesn't sign in the box "unassigned". I can view this player only with web-app

**Comment by hunterjm** [comment] 2017-02-09 21:33
Duplicate of #98

**Closed by hunterjm** 2017-02-09 21:33 UTC
Labels: duplicate

**Comment by Bob930** [comment] 2017-02-10 04:09
hunterjm, this isn't a duplicate to issue #98. The players that it has won through bidding just stay in the "bidding section" and don't even get sent to unassigned.
