### ISSUE TITLE
Weird Gui Bug

### ISSUE THREAD

**Issue by Daves10** [hunterjm/fifa-autobuyer#51] opened 2017-01-25 13:58 UTC
![bug](https://cloud.githubusercontent.com/assets/25257542/22293087/0a370ff6-e2ed-11e6-92e9-d23e3f55564c.PNG)

Hello, I'm experiencing a weird bug. Please see the picture uploaded for reference. Basically none of the buttons are working except the Play/Stop.

I've already restarted the app, then reinstalled the app and finally rebooted the PC. None have worked...

**Comment by hunterjm** [comment] 2017-01-25 17:11
It looks like your player list got corrupted somehow. Try hitting "clear list" and re-adding the players you want.

**Comment by Daves10** [comment] 2017-01-25 19:21
Thanks it worked!

Too bad we lose the info on a specific player and his contribution to lifetime profit once we take him out of the list.

**Comment by ConnorMann** [comment] 2017-01-25 20:44
@hunterjm I have also experienced this issue multiple times. Not sure what causes it.

**Comment by Daves10** [comment] 2017-01-26 17:21
I guess that new players do this. It seems that when I add players that switched clubs during this transfer window (fonte, deulofeu, markovic, depay for instance) the app bugs. All players still show their previous club on the app.

**Comment by Daves10** [comment] 2017-01-26 17:32
or having our own players in the transfer list to be sold, it seems the app doesn't handle very well with that..

**Comment by hunterjm** [comment] 2017-01-27 04:55
@Daves10 - I am seeing both versions of the card available when searching for deulofeu.  I will make a note to store the player contributions separately from the player list in the future so that removing them from the list doesn't lose their history if you ever were to add them back, and so they will still count toward lifetime profit.

**Comment by hunterjm** [comment] 2017-01-27 05:10
see #59 for keeping history.  I don't really have time to dig into the root cause of the player list being corrupted, but I am going to close this out as hitting "clear list" is a short term solution.

**Closed by hunterjm** 2017-01-27 05:10 UTC
