### ISSUE TITLE
New TOTW appears as "Unknown"

### ISSUE THREAD

**Issue by mestesso93** [hunterjm/fifa-autobuyer#115] opened 2017-02-09 20:50 UTC
I've set the AB on a new player of TOTW. If i check the log, the name appear. But if i check BUYING, SELLING, UNASSIGNED, this player appear as "unknown"

**Comment by hunterjm** [comment] 2017-02-09 21:36
Duplicate of #52

**Closed by hunterjm** 2017-02-09 21:36 UTC
Labels: duplicate

**Comment by mestesso93** [comment] 2017-02-10 00:15
ops, sorry

**Comment by hunterjm** [comment] 2017-02-10 01:39
No problem. I just try and keep the issues clean because I use them to determine what to do next (when i have a couple hours to spare)
