### ISSUE TITLE
Mad Buy 

### ISSUE THREAD

**Issue by SargentoDaPaz** [hunterjm/fifa-autobuyer#76] opened 2017-02-01 19:58 UTC
Problem:

Started the FIFA AUTO BUYER, I did not update the players, ADURIZ was to buy for 1800, when I checked the log I was buying BIN for 2500.

Can  add a button to update all players automatically?

**Comment by mestesso93** [comment] 2017-02-02 13:53
if you have set "same price relist" you must disabled it

**Comment by SargentoDaPaz** [comment] 2017-02-02 14:08
Nothing activated

**Comment by hunterjm** [comment] 2017-02-02 16:11
duplicate of #64

**Closed by hunterjm** 2017-02-02 16:11 UTC
