### ISSUE TITLE
Error Code whenever I try It tries to search for a player

### ISSUE THREAD

**Issue by MCPandora** [hunterjm/fifa-autobuyer#87] opened 2017-02-05 03:14 UTC
All I get is Error searching for bin, "FutapiStatuscode": 460, and another one that says error searching for auction instead, same error code.

**Comment by hunterjm** [comment] 2017-02-05 03:56
Duplicate of #41 - Make sure you are logged out of your console and the Web App, then try again.

**Closed by hunterjm** 2017-02-05 03:56 UTC
