### ISSUE TITLE
Autobuyer does not start.

### ISSUE THREAD

**Issue by JonasPap** [hunterjm/fifa-autobuyer#186] opened 2017-05-21 14:32 UTC
![problem buyer](https://cloud.githubusercontent.com/assets/22565982/26284756/d1617430-3e42-11e7-9665-4e24da1a4924.JPG)

I got that problem. I waited one time 1 hour and nothing changed.  Have I done something wrong? I selected a player and changed nothing in the settings and then went to bidding overview and pressed start.

**Comment by Jeuiskeh** [comment] 2017-05-21 16:25
yeah i got the same problem. I think its just a bug or something hopefully he'll fix it be patient XD

**Comment by Stuntcat** [comment] 2017-05-22 07:56
I have a feeling it may be a problem with EA's web app, the companion app has become very buggy.

**Comment by aelnaggar** [comment] 2017-05-22 08:48
same here on MacOS seems like a general bug

**Comment by JonasPap** [comment] 2017-05-22 19:24
problem still exists for me atm, same for you guys?

**Comment by dham84** [comment] 2017-05-22 19:40
Been seeing this for about a week, actually never seen it work (recently discovered it).

**Comment by marionety** [comment] 2017-05-23 08:00
Same here.

**Comment by DhananjaySherawat** [comment] 2017-05-26 07:09
Its not working,i thought it was a temporary ban but i can search from my web app,but i gets stuck on updating prices .This has been like this for a week now, Its the best autobuyer for fifa and i am an ardent fan of it,hope they fix the issue soon.

**Comment by marionety** [comment] 2017-05-26 07:47
There is a problem with the response on bid.js, line 93
it's not returning the object auctionInfo that is needed after. I can't fix it right now, hope someone can.

`try {
      binResponse = await api.search(binFilter);
    } catch (e) {
      dispatch(addMessage('error', 'Error searching for BIN on ${player.name}', e));
      binResponse = { auctionInfo: [] };
    }
    console.log(binResponse);
    if (binResponse.auctionInfo) {`

**Comment by DhananjaySherawat** [comment] 2017-05-26 12:00
I think hunter would be working on it Maybe but there hasn't been any reply or statement from him. I Hope he is working on it and if he could just tell us that he is indeed working on it , everyone would breath a sigh of relief because THIS AB IS THE BEST

**Comment by DhananjaySherawat** [comment] 2017-05-31 16:15
when is this going to be fixed ???????

**Comment by TomPalin** [comment] 2017-05-31 18:54
Im still having this problem on MacOS. I hope its fixed soon enough for TOTS Liga Santander.

**Comment by DhananjaySherawat** [comment] 2017-06-01 06:23
i am hoping for the same brother

**Comment by Trishift** [comment] 2017-06-03 01:58
@marionety Did you end up fixing it?

**Comment by TomPalin** [comment] 2017-06-04 08:52
I can confirm it has been fixed in the new update about now. Thanks so much Hunter. Really appreciate the hard work

**Comment by JonasPap** [comment] 2017-06-04 12:00
do you guys have any tipps how to make the best profit? how im using it atm i make like 5-10k an hour. an thats not very much.

**Closed** 2017-06-13 22:49 UTC
